### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by o-jasper** [luakit/luakit-plugins#10]
They are marked with copyright, but it is not clear which one. Suggest GPLv3.

**Comment by Plaque-fcc** [comment]
Why not?
PR?

**Comment by aidanholm** [comment]
I'm going to say GPLv3 as well, although I'm not sure of the license under which these modules were originally submitted. I feel it's unlikely to ever be contested though.
This is easy enough; I'll do this now.

**Comment by aidanholm** [comment]
Done!

**Comment by Plaque-fcc** [comment]
I insist on the most fresh GPL where I am the author. adblock was under GPLv2 IIRC; far long ago when I picked it up.

On August 21, 2017 8:40:36 PM GMT+03:00, Aidan Holm <notifications@github.com> wrote:
>I'm going to say GPLv3 as well, although I'm not sure of the license
>under which these modules were originally submitted. I feel it's
>unlikely to ever be contested though.
>This is easy enough; I'll do this now.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/luakit/luakit-plugins/issues/10#issuecomment-323806840

-- 
J.K.

**Comment by aidanholm** [comment]
Sure; it's all GPLv3 now :) and if any of the original authors complain we can add an exception for their modules, of course

**Comment by Plaque-fcc** [comment]
I mentioned everyone in © lines along the code.

On August 21, 2017 8:47:51 PM GMT+03:00, Aidan Holm <notifications@github.com> wrote:
>Sure; it's all GPLv3 now :) and if any of the original authors complain
>we can add an exception for their modules, of course
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/luakit/luakit-plugins/issues/10#issuecomment-323808357

-- 
J.K.
