### ISSUE TITLE
Cannot load plugins 

### ISSUE THREAD

**Issue by sadger** [luakit/luakit-plugins#11]
Using current develop branch from luakit (ref commit 16f8b89).
I clone the plugin folder to my ~/.config/luakit/plugins and change my rc.lua to include the line
'require "plugins"' but when I try and launch luakit with the plugins enabled I always get an error message:

```
Initializing plugins: scanning subfolders for valid entries…
plugins: reading rc.lua…
plugins: rc file exists.
Initializing plugin 'adblock'…
./lib/chrome.lua:162: attempt to index local 'webview' (a nil value)
[    0.036598] E: luakit: main:187: no windows spawned by rc file, exiting
```

I believe I have followed the instructions correctly to setting it up. Perhaps you can offer some help in getting it working. I'm particularly interesting in getting adblock set up.

**Comment by Plaque-fcc** [comment]
I'm pretty sure there's no webview required at the moment you require
plugins. Take a look at this and note the sequence:

$ egrep 'webview|plugins' ~/.config/luakit/rc.lua 
-- Load users webview class
-- ("$XDG_CONFIG_HOME/luakit/webview.lua" or "/etc/xdg/luakit/webview.lua")
require "webview"
-- NoScript plugin, toggle scripts and or plugins on a per-domain basis.
-- `,ts` to toggle scripts, `,tp` to toggle plugins, `,tr` to reset.
-- Remove all "enable_scripts" & "enable_plugins" lines from your
require "plugins"

**Comment by Plaque-fcc** [comment]
And I have to inform you that current AdBlock plugin's algorithm will
slow down loading resources in Luakit significantly. I wish one day I
will refactor its code.

**Comment by sadger** [comment]
Ok thanks. I included it after all the other "require" statements and it seemed to work. So thanks for that. Maybe the readme can be updated to specifically say where to include it? Or is it obvious if you know lua? I'll bear in mind the slowness thanks.

**Comment by Plaque-fcc** [comment]
I'm gonna check that; but it's rather logical.

Moreover, there was a proposal about moving custom settings to
userprefs.lua file if it exists. Probably it's a good idea rather than
merging your local rc.lua config with the default one.

**Comment by Plaque-fcc** [comment]
#### Installing
…
###### If you have no "rc.lua" in "~/.config/luakit/", then it takes no effect, so copy one from "/etc/xdg/luakit/" and find there text like "-- Optional user script loading --". Let us place 'require("plugins")' after that text, so plugins will be loaded.

**Comment by sadger** [comment]
Oh ok thanks. I must have skimmed over that bit.

**Comment by Plaque-fcc** [comment]
This was the fault by «just do as we say» without any logical
explanation expressed. One day plugins wiki will be refactored too.

**Comment by aidanholm** [comment]
I'm closing this since it's a question regarding the old version of luakit. There are some problems with the main plugin `init.lua`; I'll open separate issues for those.
