### ISSUE TITLE
Plugins break ':help' luakit introspection.

### ISSUE THREAD

**Issue by Plaque-fcc** [luakit/luakit-plugins#3]
At least, 'oldschoolkeys' does.

Upd0: Since the introspection mechanism still needs to be documented more so I can't decide it mistreats plugins or plugins do violate it; thus, this issue affects plugins more than luakit.

**Comment by mason-larobina** [comment]
This fix has been merged upstream.

**Comment by Plaque-fcc** [comment]
Good to see you're back during this merge session.

Luakit is Awesome! (And you know why I said so.)
