### ISSUE TITLE
AdBlock can make Luakit hang up or crash.

### ISSUE THREAD

**Issue by Plaque-fcc** [luakit/luakit-plugins#4]
When enabled, luakit-adblock can make Luakit hang up or even crash by segfault on several sites.

Listing here those confirmed sites to compare:

• [Lurkmore](http://lurkmore.to/)

(To be continued…)

**Comment by aidanholm** [comment]
The adblock in this repo is out of date for the current version of luakit, and the main repo includes a compatible adblocker, so I'm going to close this.
